# Generated by Django 4.1 on 2023-09-30 17:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 30, 17, 59, 42, 628918, tzinfo=datetime.timezone.utc)),
        ),
    ]
